---
title: "Air pressure: drift"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_width: 7
    fig_height: 4
    toc: true
    toc_depth: 4
    number_sections: false
    df_print: paged # default, kable, tibble
    fig_caption: true
  pdf_document:
    toc: true
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{Air pressure: drift}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This is an advanced guide. It explains how `detect_drift()` works for air pressure data. Make sure you have first read the [getting started](gwloggeR.html) material.

Drift is defined as "a continuous or incremental change over time in indication due to changes in metrological properties of a measuring instrument."

## Air pressure model

For outlier detection in air pressure data we used a simple gaussian noise model: it is simple and easy to interpret. For drift detection this gaussian noise model is inadequate. The problem is correlation between subsequent observations, which directly affects significance calculation of drifts.

So what is a good air pressure model? In drift analysis 19/19b we did some testing with a full range of ARIMA models on all available barometer data. From that we have seen that there is a significant drop in likelihood from ARIMA(0,0,0) with non-zero mean to ARIMA(1,0,0) with non-zero mean. Subsequent more complex ARIMA models did not result in much better likelihoods -- although the AIC/BIC test sometimes suggested otherwise.

A noteworthy observation was that ARIMA(0,1,0) performed almost equally well as the ARIMA(1,0,0) with non-zero mean. When $\phi$ is close to 1 these two models are equivalent, and that explains the similar performance. At the same time it must be noted that air pressure does _not_ behave like a random walk, which will be explained later.

So the chosen model for air pressure was ARIMA(1,0,0) with non-zero mean -- shorthand AR(1). In formulaic notation (TODO: Box & Jenkins):

$$
z_t - \mu = \phi_1(z_{t-1} - \mu) + a_t
$$
where $a_t \sim \mathcal{N}(0, \sigma^2)$. For a more succinct notation one can use $\tilde{z}_t = z_t - \mu$.

### Estimation of $\phi$

Interesting is how the autoregressive parameter $\phi$ behaves in function of $\Delta t$, the time interval between measurements. If we were to measure the air pressure each minute, we would see that subsequent measurements are almost identical -- apart from intrinsic barometer error. The series would behave almost as a random walk. Almost, because although $\phi$ would be close to 1, it would never be exactly 1. One way to see this is that the air pressure is stationary, while a random walk is not. The $\phi = 1 - \epsilon$, however small $\epsilon$ may be, will pull the series towards $\mu$, and thus result in stationary series.

On the other extreme, if we would measure air pressure each 2 months (cf. drift analysis 18), we would see no correlation at all between subsequent measurements. In other words, $\phi$ would be 0 and the resulting model would be simple gaussian noise: $z_t = \mu + a_t$.

This analysis thus suggests that $\phi$ is a function of $\Delta t$. Unfortunately, the classical ARIMA models allow only for fixed $\Delta t$. That is why the algorithm currently aggregates the measurements to 12h intervals (i.e. it is assumed that $\Delta t = 12h$).

Under $\Delta t = 12h$ we can estimate $\phi$ based on all available barometer data. This estimation suggests that $0.80 \le \phi(12h) \le 0.90$. Knowing this, it seems plausible to assume the parameter as know _a-prior_ information, instead of estimating it each time on each series separately. (Cf. drift analysis 28/29)

## Difference with reference series model

For drift detection we use the difference with a reference series $d_t$, not the original series $z_t$. So it begs the question: how does $\phi$ translate for $d_t$. Assume we have $r_t$ as our reference series and assume that both $z_t$ and $r_t$ are height compensated, making $\mu_z = \mu_r = \mu$. Set $b_t = a_{z,t} - a_{r,t}$. Then:

$$
\begin{aligned}
d_t &= z_t - r_t \\
    &= \tilde{z}_t - \tilde{r}_t \\
    &= b_t + \phi(\tilde{z}_{t-1} - \tilde{r}_{t-1}) \\
    &= b_t + \phi b_{t-1} + \phi(\tilde{z}_{t-2} - \tilde{r}_{t-2}) \\
    &= b_t + \phi b_{t-1} + \phi^2 b_{t-2} + \phi^3 b_{t-3} + \dots \\
    &= \phi d_{t - 1} + b_t
\end{aligned}
$$

The last equivalence one can see by just expanding $\phi d_{t-1}$ recursively. TODO: If we do not assume height compensation, then ...

Three things are worth to note here. First is that $d_t$ is still an AR(1) model. Second is that the AR(1) parameter is the same as in $z_t$ and $r_t$: just $\phi$. And the last thing is that only the error is different: $a_t - a_t$. This error-term we investigate next.

### The error term $b_t$

We assumed in our model definition that $a_t \sim \mathcal{N}(0, \sigma^2)$. This makes $b_t \sim \mathcal{N}(0, 2\sigma^2 - 2\text{cov}(a_{z,t}, a_{r,t}))$. In drift analysis 19 we estimated $\sigma^2 \approx 25$ and $\text{var}(b_t) \approx 2.2$. This suggest $\text{cov}(a_{z,t}, a_{r,t}) \approx 23.9$ and thus very high correlation between $z_t$ and $r_t$. This effect can be seen in the following plot (TODO):

## Drift detection

For drift detection we use the series $d_t$. This is because $b_t$ has much lower variance than $a_t$, making drift detection much more sensitive. The resulting drift detection model is this:

$$
d_t - \mu_d -  \delta(t-t_\delta)I(t\ge t_\delta) - \mathbf{\beta} \mathbf{x_t} 
  = \phi[d_{t-1} - \mu_d -  \delta(t-1-t_\delta)I(t-1\ge t_\delta) - \mathbf{\beta} \mathbf{x_{t-1}} ] + b_t
$$
where $\mathbf{x_t}$ are the yearly seasonal sine and cosine components and $\mu_d$, $\mathbf{\beta}$, $\sigma_d^2$, $\delta$ and $t_\delta$ are to be estimated. These estimates can be recovered with the `detect_drift(verbose=TRUE)` parameter.

### Estimation of $\delta$ and $t_\delta$

Parameters $\delta$ and $t_\delta$ are maximum likelihood estimates (MLE). Due to discrete and non-linear nature of $t_\delta$ the maximization of the likelihood function is not straightforward. A secondary difficulty is that the AR(1) likelihood function is not convex either (TODO REF). The `arima()` function seems to produced good results, despite the convexity. The first problem we solve brute-force by fitting the AR(1) model to specific $t_\delta$. Instead of fitting the AR(1) model for each possible $t_\delta$, we scan in steps of $\sqrt{N/2}$ where $N$ is the number of observations. Subsequently we do a local search on all $t$ in the vicinity of the optima. 

### Drift significance

Once $\hat{\delta}_{MLE}$ and $\hat{t}_{\delta_{MLE}}$ have been found, likelihood ratio test is used to test their significance. A peculiar observation here is the fact that the optimal $\chi^2$ degrees of freedom are not equal to 2, but to some unknown $2 + f(N)$ where $0 < f(N) < 1$. For our case, where $1000 < N < 10000$, it seems that $f(N) \approx 0.8$ performs well in the sense that under $H_0$ the $p$-values are distributed uniformly. Currently it is not clear in what sense the drift model violates the Wilks theorem (TODO REF), and thus what $f$ is.

## Examples

TODO

## Future work

* Implement $\phi(\Delta t)$ (i.e. dependence of $\phi$ on time differences.)
* Bayesian estimation of $\delta$ and $t_\delta$.
* Investigate the unexpected $N$-dependence in degrees of freedom of the LR test.

## References
